In [6]:
import pandas as pd

COMMODITY = 'nickel'
PRICE_FILE = f'{COMMODITY}_prices.csv'
filename = 'Nickel 2020 - 2023.xlsx'
sheet = 'Global Search Data'

df = pd.read_excel(filename, sheet_name=sheet, skiprows=1)
df = df.rename(columns={'Value $' : 'Value'})
csv = df.to_csv(f'{COMMODITY}.csv')
df

,Date,HS Code,Product Description,Consignee,Shipper,Notify Party Name,Std. Quantity,Std. Unit,Gross Weight,Quantity,...,Actual Duty,Port of Delivery,Container TEU,Freight Term,Marks Number,Consignee Address,Shipper Address,Notify Party Address,HS Product Description,Country Name
0,2020-07-22,2833240000,"NICKEL SULFATE,25KG/BAG",HAMBURG MOVERS COMPANY LIMITED,HAOYANG TRADING LIITED,NaN,725.00,KGS,0.00,725.00,...,-,-,-,-,-,98403 80100 MOMBASA,"SAN PO KONG KL,CHINA",NaN,NaN,Kenya T3 Import
1,2020-06-08,28332400,NICKEL (II) SULPHATE HEXAHYDR | SIGMA | 227676...,EMPRESA CL202006 000117,NaN,NaN,0.30,KGS,172.00,0.30,...,-,-,-,-,-,NaN,NaN,NaN,NICKEL SULPHATE,Chile T2 Import
2,2020-02-13,2833240000,NOT AVAILABLE | INFO,BYC ECUADOR SA,BYCSA SA,NaN,1300.00,KGS,1333.41,1300.00,...,-,-,-,-,-,LOTIZSACION SATIRON AV FELIPE CAMPUZANO TERCER...,NaN,NaN,OF NICKEL,Columbia T3 Export
3,2020-08-04,28332400,SUMITOMO NICKEL SULPHATE,PT LAUTAN LUAS TBK,UYEMURA INTERNATIONAL SINGAPORE,NaN,6000.00,KGS,0.00,6000.00,...,2.5,-,-,-,-,"Graha Indramas, Gedung, Jl. Ks. Tubun No.77, R...","PTE LTD NO.2 JURONG EAST ST.21, #05-22/23 IMM ...",NaN,NaN,Indonesia T3 Import
4,2020-01-29,2833240000,"DO: 13GCOCT0120043, ORDER NUMBER / PURCHASE OR...",COMPA IA COLOMBIANA DE CERAMICA SA COLCERAMICA SA,AMPERE INDUSTRIE SAS,NaN,1000.00,KGS,1015.00,1000.00,...,-,-,-,-,-,CL 113 7 80 P 3 TO AR,95075 CERGY PONTOISE CEDEX FRANCE,NaN,OF NICKEL,Columbia T3+ Import
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18880,2023-08-01,28332400,SULPHATES OF NICKEL,NaN,NaN,NaN,2.00,TON,0.00,2.00,...,-,-,-,-,-,NaN,NaN,NaN,NaN,Estonia T1 Import
18881,2023-08-01,28332400,SULPHATES OF NICKEL,NaN,NaN,NaN,1.92,TON,0.00,1.92,...,-,-,-,-,-,NaN,NaN,NaN,NaN,Slovakia T1 Import
18882,2023-09-01,28332400,SULPHATES OF NICKEL,NaN,NaN,NaN,0.36,TON,0.00,0.36,...,-,-,-,-,-,NaN,NaN,NaN,NaN,Bulgaria T1 Import
18883,2023-07-01,28332400,SULPHATES OF NICKEL,NaN,NaN,NaN,1.86,TON,0.00,1.86,...,-,-,-,-,-,NaN,NaN,NaN,NaN,Sweden T1 Import
18884,2023-07-01,28332400,SULPHATES OF NICKEL,NaN,NaN,NaN,2.79,TON,0.00,2.79,...,-,-,-,-,-,NaN,NaN,NaN,NaN,Denmark T1 Import

In [7]:
# Convert Price csv date format

price_df = pd.read_csv(PRICE_FILE)
 
# Convert 'Date' column to datetime format
price_df['Date'] = pd.to_datetime(price_df['Date'])

# Format 'Date' column to 'MMM DD, YYYY' format
price_df['Date'] = price_df['Date'].dt.strftime('%b %d, %Y')

price_df.to_csv(PRICE_FILE)