In [1]:
import numpy as np
import pandas as pd

In [3]:
pd.read_csv('copper_oec_trade_data.csv')

,year,exporter_name,export_value,export_quantity,Average Closing Price
0,2021,Argentina,84866.0,464.116,4.2445
1,2021,Papua New Guinea,824483969.0,274995.030,4.2445
2,2021,Philippines,667784705.0,151679.802,4.2445
3,2021,Hong Kong,1403927.0,3336.607,4.2445
4,2021,Pakistan,13029808.0,9144.323,4.2445
...,...,...,...,...,...
999,2012,Netherlands,12597000.0,6632.776,3.6101
1000,2012,China,2183273.0,1954.038,3.6101
1001,2012,Finland,23927.0,0.616,3.6101
1002,2012,Republic of the Congo,532828.0,205.807,3.6101
1003,2012,Algeria,948.0,0.195,3.6101

In [115]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.compose import ColumnTransformer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv1D, MaxPooling1D, Dropout

# Step 1: Data Preparation
data = pd.read_csv("copper_oec_trade_data.csv")

# Extract features and target variable
features = []
target = []

# One-hot encode exporter_name
encoder = LabelEncoder()
exporter_encoded = encoder.fit(data[['exporter_name']])

scaler = StandardScaler()
features_scaled = scaler.fit(data[['export_value','export_quantity']])


# print(len(encoder.classes_))

for year,group in data.groupby('year'):
    arr = np.ones(shape = (len(encoder.classes_),3))*-1    
    num_features = scaler.transform(group[['export_value','export_quantity']])
    cat_features = encoder.transform(group[['exporter_name']])
    
    temp = np.column_stack((num_features,cat_features))
    # print(temp)
    for i in range(len(temp)):
        arr[i] = temp[i]
    target.append(group['Average Closing Price'].mean())
    
    features.append(arr)
    
features = np.array(features)
target = np.array(target)
    
    
# features = features.drop(['exporter_name'], axis=1, inplace=True)

# # Normalize numerical features
# scaler = StandardScaler()
# features_scaled = scaler.fit_transform(features)





# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=50)

print(X_train.shape)

(8, 159, 3)

/Users/harshdeepsingh/miniconda/envs/lab_v2/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/harshdeepsingh/miniconda/envs/lab_v2/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
/Users/harshdeepsingh/miniconda/envs/lab_v2/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
/Users/harshdeepsingh/miniconda/envs/lab_v2/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
/Users/harshdeepsingh/miniconda/envs/lab_v2/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
/Users/harshdeepsingh/miniconda/envs/lab_v2/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
/Users/harshdeepsingh/miniconda/envs/lab_v2/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
/Users/harshdeepsingh/miniconda/envs/lab_v2/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
/Users/harshdeepsingh/miniconda/envs/lab_v2/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
/Users/harshdeepsingh/miniconda/envs/lab_v2/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
/Users/harshdeepsingh/miniconda/envs/lab_v2/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [116]:
# Step 2: Model Definition
model = Sequential()
model.add(Conv1D(32, kernel_size=3, activation='relu', input_shape=(features.shape[1],features.shape[2])))
# model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='linear'))  # Linear activation for regression

model.summary()

# Step 3: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_squared_error'])

# Step 4: Train the Model
model.fit(X_train, y_train, epochs=100, batch_size=10)

# Step 5: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f'Mean Squared Error on Test Data: {loss}')

# Make predictions
predictions = model.predict(X_test)

Model: "sequential_19"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv1d_11 (Conv1D)          (None, 157, 32)           320

 flatten_11 (Flatten)        (None, 5024)              0

 dense_44 (Dense)            (None, 16)                80400

 dense_45 (Dense)            (None, 1)                 17

=================================================================
Total params: 80737 (315.38 KB)
Trainable params: 80737 (315.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/100
1/1 [==============================] - 0s 128ms/step - loss: 60.0098 - mean_squared_error: 60.0098
Epoch 2/100
1/1 [==============================] - 0s 2ms/step - loss: 1541.2762 - mean_squared_error: 1541.2762
Epoch 3/100
1/1 [==============================] - 0s 3ms/step - loss: 318.8155 - mean_squared_error: 318.8155
Epoch 4/100
1/1 [==============================] - 0s 3ms/step - loss: 134.7680 - mean_squared_error: 134.7680
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: 200.0319 - mean_squared_error: 200.0319
Epoch 6/100
1/1 [==============================] - 0s 3ms/step - loss: 179.3542 - mean_squared_error: 179.3542
Epoch 7/100
1/1 [==============================] - 0s 2ms/step - loss: 149.0048 - mean_squared_error: 149.0048
Epoch 8/100
1/1 [==============================] - 0s 3ms/step - loss: 109.3198 - mean_squared_error: 109.3198
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: 67.2025 - mean_squared_error: 67.2025
Epoch 10/100
1/1 [==============================] - 0s 2ms/step - loss: 37.4185 - mean_squared_error: 37.4185
Epoch 11/100
1/1 [==============================] - 0s 2ms/step - loss: 21.6449 - mean_squared_error: 21.6449
Epoch 12/100
1/1 [==============================] - 0s 2ms/step - loss: 12.5517 - mean_squared_error: 12.5517
Epoch 13/100
1/1 [==============================] - 0s 3ms/step - loss: 10.3845 - mean_squared_error: 10.3845
Epoch 14/100
1/1 [==============================] - 0s 2ms/step - loss: 11.6799 - mean_squared_error: 11.6799
Epoch 15/100
1/1 [==============================] - 0s 2ms/step - loss: 13.3752 - mean_squared_error: 13.3752
Epoch 16/100
1/1 [==============================] - 0s 2ms/step - loss: 15.1639 - mean_squared_error: 15.1639
Epoch 17/100
1/1 [==============================] - 0s 2ms/step - loss: 16.9225 - mean_squared_error: 16.9225
Epoch 18/100
1/1 [==============================] - 0s 2ms/step - loss: 18.0984 - mean_squared_error: 18.0984
Epoch 19/100
1/1 [==============================] - 0s 3ms/step - loss: 18.1600 - mean_squared_error: 18.1600
Epoch 20/100
1/1 [==============================] - 0s 3ms/step - loss: 17.4310 - mean_squared_error: 17.4310
Epoch 21/100
1/1 [==============================] - 0s 3ms/step - loss: 16.0610 - mean_squared_error: 16.0610
Epoch 22/100
1/1 [==============================] - 0s 2ms/step - loss: 14.2515 - mean_squared_error: 14.2515
Epoch 23/100
1/1 [==============================] - 0s 3ms/step - loss: 12.2095 - mean_squared_error: 12.2095
Epoch 24/100
1/1 [==============================] - 0s 4ms/step - loss: 10.1410 - mean_squared_error: 10.1410
Epoch 25/100
1/1 [==============================] - 0s 4ms/step - loss: 8.2861 - mean_squared_error: 8.2861
Epoch 26/100
1/1 [==============================] - 0s 3ms/step - loss: 6.6713 - mean_squared_error: 6.6713
Epoch 27/100
1/1 [==============================] - 0s 3ms/step - loss: 5.2450 - mean_squared_error: 5.2450
Epoch 28/100
1/1 [==============================] - 0s 4ms/step - loss: 4.2320 - mean_squared_error: 4.2320
Epoch 29/100
1/1 [==============================] - 0s 3ms/step - loss: 3.6322 - mean_squared_error: 3.6322
Epoch 30/100
1/1 [==============================] - 0s 4ms/step - loss: 3.3969 - mean_squared_error: 3.3969
Epoch 31/100
1/1 [==============================] - 0s 2ms/step - loss: 3.3677 - mean_squared_error: 3.3677
Epoch 32/100
1/1 [==============================] - 0s 3ms/step - loss: 3.5058 - mean_squared_error: 3.5058
Epoch 33/100
1/1 [==============================] - 0s 9ms/step - loss: 3.7691 - mean_squared_error: 3.7691
Epoch 34/100
1/1 [==============================] - 0s 20ms/step - loss: 4.0769 - mean_squared_error: 4.0769
Epoch 35/100
1/1 [==============================] - 0s 7ms/step - loss: 4.3596 - mean_squared_error: 4.3596
Epoch 36/100
1/1 [==============================] - 0s 8ms/step - loss: 4.5658 - mean_squared_error: 4.5658
Epoch 37/100
1/1 [==============================] - 0s 3ms/step - loss: 4.6653 - mean_squared_error: 4.6653
Epoch 38/100
1/1 [==============================] - 0s 6ms/step - loss: 4.6491 - mean_squared_error: 4.6491
Epoch 39/100
1/1 [==============================] - 0s 6ms/step - loss: 4.5271 - mean_squared_error: 4.5271
Epoch 40/100
1/1 [==============================] - 0s 3ms/step - loss: 4.3233 - mean_squared_error: 4.3233
Epoch 41/100
1/1 [==============================] - 0s 3ms/step - loss: 4.0700 - mean_squared_error: 4.0700
Epoch 42/100
1/1 [==============================] - 0s 2ms/step - loss: 3.8022 - mean_squared_error: 3.8022
Epoch 43/100
1/1 [==============================] - 0s 3ms/step - loss: 3.4943 - mean_squared_error: 3.4943
Epoch 44/100
1/1 [==============================] - 0s 2ms/step - loss: 3.1805 - mean_squared_error: 3.1805
Epoch 45/100
1/1 [==============================] - 0s 3ms/step - loss: 2.9315 - mean_squared_error: 2.9315
Epoch 46/100
1/1 [==============================] - 0s 2ms/step - loss: 2.7662 - mean_squared_error: 2.7662
Epoch 47/100
1/1 [==============================] - 0s 2ms/step - loss: 2.6869 - mean_squared_error: 2.6869
Epoch 48/100
1/1 [==============================] - 0s 2ms/step - loss: 2.5782 - mean_squared_error: 2.5782
Epoch 49/100
1/1 [==============================] - 0s 3ms/step - loss: 2.4149 - mean_squared_error: 2.4149
Epoch 50/100
1/1 [==============================] - 0s 2ms/step - loss: 2.3085 - mean_squared_error: 2.3085
Epoch 51/100
1/1 [==============================] - 0s 3ms/step - loss: 2.2504 - mean_squared_error: 2.2504
Epoch 52/100
1/1 [==============================] - 0s 3ms/step - loss: 2.2213 - mean_squared_error: 2.2213
Epoch 53/100
1/1 [==============================] - 0s 2ms/step - loss: 2.1974 - mean_squared_error: 2.1974
Epoch 54/100
1/1 [==============================] - 0s 3ms/step - loss: 2.1561 - mean_squared_error: 2.1561
Epoch 55/100
1/1 [==============================] - 0s 4ms/step - loss: 2.0805 - mean_squared_error: 2.0805
Epoch 56/100
1/1 [==============================] - 0s 2ms/step - loss: 1.9630 - mean_squared_error: 1.9630
Epoch 57/100
1/1 [==============================] - 0s 2ms/step - loss: 1.8051 - mean_squared_error: 1.8051
Epoch 58/100
1/1 [==============================] - 0s 2ms/step - loss: 1.6166 - mean_squared_error: 1.6166
Epoch 59/100
1/1 [==============================] - 0s 2ms/step - loss: 1.4124 - mean_squared_error: 1.4124
Epoch 60/100
1/1 [==============================] - 0s 2ms/step - loss: 1.2089 - mean_squared_error: 1.2089
Epoch 61/100
1/1 [==============================] - 0s 2ms/step - loss: 1.0210 - mean_squared_error: 1.0210
Epoch 62/100
1/1 [==============================] - 0s 3ms/step - loss: 0.8592 - mean_squared_error: 0.8592
Epoch 63/100
1/1 [==============================] - 0s 2ms/step - loss: 0.7285 - mean_squared_error: 0.7285
Epoch 64/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6283 - mean_squared_error: 0.6283
Epoch 65/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5536 - mean_squared_error: 0.5536
Epoch 66/100
1/1 [==============================] - 0s 2ms/step - loss: 0.4967 - mean_squared_error: 0.4967
Epoch 67/100
1/1 [==============================] - 0s 2ms/step - loss: 0.4494 - mean_squared_error: 0.4494
Epoch 68/100
1/1 [==============================] - 0s 3ms/step - loss: 0.4046 - mean_squared_error: 0.4046
Epoch 69/100
1/1 [==============================] - 0s 2ms/step - loss: 0.3577 - mean_squared_error: 0.3577
Epoch 70/100
1/1 [==============================] - 0s 3ms/step - loss: 0.3073 - mean_squared_error: 0.3073
Epoch 71/100
1/1 [==============================] - 0s 2ms/step - loss: 0.2544 - mean_squared_error: 0.2544
Epoch 72/100
1/1 [==============================] - 0s 2ms/step - loss: 0.2020 - mean_squared_error: 0.2020
Epoch 73/100
1/1 [==============================] - 0s 2ms/step - loss: 0.1540 - mean_squared_error: 0.1540
Epoch 74/100
1/1 [==============================] - 0s 2ms/step - loss: 0.1137 - mean_squared_error: 0.1137
Epoch 75/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0835 - mean_squared_error: 0.0835
Epoch 76/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0638 - mean_squared_error: 0.0638
Epoch 77/100
1/1 [==============================] - 0s 4ms/step - loss: 0.0537 - mean_squared_error: 0.0537
Epoch 78/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0508 - mean_squared_error: 0.0508
Epoch 79/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0521 - mean_squared_error: 0.0521
Epoch 80/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0548 - mean_squared_error: 0.0548
Epoch 81/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0564 - mean_squared_error: 0.0564
Epoch 82/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0558 - mean_squared_error: 0.0558
Epoch 83/100
1/1 [==============================] - 0s 6ms/step - loss: 0.0526 - mean_squared_error: 0.0526
Epoch 84/100
1/1 [==============================] - 0s 18ms/step - loss: 0.0473 - mean_squared_error: 0.0473
Epoch 85/100
1/1 [==============================] - 0s 19ms/step - loss: 0.0412 - mean_squared_error: 0.0412
Epoch 86/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0354 - mean_squared_error: 0.0354
Epoch 87/100
1/1 [==============================] - 0s 4ms/step - loss: 0.0309 - mean_squared_error: 0.0309
Epoch 88/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0283 - mean_squared_error: 0.0283
Epoch 89/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0275 - mean_squared_error: 0.0275
Epoch 90/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0281 - mean_squared_error: 0.0281
Epoch 91/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0292 - mean_squared_error: 0.0292
Epoch 92/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0302 - mean_squared_error: 0.0302
Epoch 93/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0304 - mean_squared_error: 0.0304
Epoch 94/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0294 - mean_squared_error: 0.0294
Epoch 95/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0272 - mean_squared_error: 0.0272
Epoch 96/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0242 - mean_squared_error: 0.0242
Epoch 97/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0208 - mean_squared_error: 0.0208
Epoch 98/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0174 - mean_squared_error: 0.0174
Epoch 99/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0146 - mean_squared_error: 0.0146
Epoch 100/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0124 - mean_squared_error: 0.0124
1/1 [==============================] - 0s 46ms/step - loss: 0.1252 - mean_squared_error: 0.1252
Mean Squared Error on Test Data: [0.12523102760314941, 0.12523102760314941]
1/1 [==============================] - 0s 24ms/step

In [117]:
y_test

array([2.7218, 2.8013])

In [118]:
predictions

array([[2.22474  ],
       [2.7430475]], dtype=float32)

In [4]:
data = pd.read_csv('/Users/harshdeepsingh/ASU/Lab_V2/GSN/onr_price_prediction/volza/magnesium/magnesium_volza_ais_price.csv',delimiter='|',on_bad_lines='skip')

In [7]:
data.sort_values('arrival_time')

,mmsi,arrival_time,arrival_port,arrival_area,departure_port,departure_time,departure_area,origin_country_code,destination_country_code,origin_country,...,Container TEU,Freight Term,Marks Number,HS Product Description,Gross Weight,Consignee Address,Shipper Address,Notify Party Address,Country Name,Magnesium Spot Price(Yen)
0,273000019,2021-03-24T17:48:15.000+05:30,RULED,StPetersburg,CNXMN,2021-02-16T22:15:39.000-07:00,Xiamen,CN,RU,China,...,-,-,-,"UNWROUGHT MAGNESIUM, CONTAINING >= 99,8% BY WE...",20060.0,NaN,NaN,NaN,Russia T3 Import,15350.0
1,444000000,2021-12-28T09:34:14.840+05:30,INBOM,Mumbai,CNDLC,2021-12-27T20:48:44.560-07:00,Dalian,CN,IN,China,...,-,-,-,"Magnesium and articles thereof, including wast...",0.0,99/2/1 & 9 MADHUBAN INDUSTRIAL ESTATE MADHUBAN...,22 MALACCA STREET # 04-03 RD CAPITA L BUILDING...,NaN,India T3 Import,48500.0
2,444000000,2021-12-28T09:34:14.840+05:30,INBOM,Mumbai,CNDLC,2021-12-27T20:48:44.560-07:00,Dalian,CN,IN,China,...,-,-,-,"Magnesium and articles thereof, including wast...",0.0,"\""||||48500.0\n444000000|2021-12-28T09:34:14.8...",NaN,NaN,NaN,48500.0
3,444000000,2021-12-28T09:34:14.840+05:30,INBOM,Mumbai,CNDLC,2021-12-27T20:48:44.560-07:00,Dalian,CN,IN,China,...,-,-,-,"Magnesium and articles thereof, including wast...",0.0,99/2/1 & 9 MADHUBAN INDUSTRIAL ESTATE MADHUBAN...,22 MALACCA STREET # 04-03 RD CAPITA L BUILDING...,NaN,India T3 Import,48500.0
4,444000000,2021-12-28T09:34:14.840+05:30,INBOM,Mumbai,CNDLC,2021-12-27T20:48:44.560-07:00,Dalian,CN,IN,China,...,-,-,-,"Magnesium and articles thereof, including wast...",0.0,"ESTATE , PURNA VILLAGE , TALUKA :",NaN,NaN,NaN,48500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31818,373128000,2022-12-30T13:45:18.000+05:30,VNHPH,Haiphong,CNSHA,2022-12-25T22:25:31.000-07:00,Shanghai,CN,VN,China,...,-,-,-,NaN,0.0,"32 THAN NHAN TRUNG STREET,",NaN,NaN,NaN,21650.0
31819,371590000,2022-12-30T18:50:01.000+05:30,USLTT,"Levittown,PA",TRYIK,2022-12-01T15:07:17.150-07:00,Yesilovacik,TR,US,Turkey,...,0,-,NO MARKS,NaN,43670.0,BUILDING 8 356 GETTY AVENUECLIFTON NJ 07011UNI...,CAMI SERIF MH. ISMET INONU BLV. |NO 82 BATIHAN...,BUILDING 8 356 GETTY AVENUECLIFTON NJ 07011UNI...,USA T3+ Import,21650.0
31820,371590000,2022-12-30T18:50:01.000+05:30,USLTT,"Levittown,PA",TRYIK,2022-12-01T15:07:17.150-07:00,Yesilovacik,TR,US,Turkey,...,0,-,NO MARKS,NaN,43670.0,BUILDING 8 356 GETTY AVENUECLIFTON NJ 07011UNI...,CAMI SERIF MH. ISMET INONU BLV. |NO 82 BATIHAN...,BUILDING 8 356 GETTY AVENUECLIFTON NJ 07011UNI...,USA T3+ Import,21650.0
31821,351453000,2022-12-30T21:10:03.000+05:30,VNHPH,Haiphong,CNSHA,2022-12-25T22:38:56.240-07:00,Shanghai,CN,VN,China,...,-,-,-,NaN,0.0,"32, 139/8 Nguyen Ngoc Vu, Trung Hoa Ward, Cau ...",RM 2,NaN,Vietnam T3 Import,21650.0
31822,351453000,2022-12-30T21:10:03.000+05:30,VNHPH,Haiphong,CNSHA,2022-12-25T22:38:56.240-07:00,Shanghai,CN,VN,China,...,-,-,-,NaN,0.0,"32 THAN NHAN TRUNG STREET,",NaN,NaN,NaN,21650.0